spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
server:
  port: 8787